import SwiftUI
import TopTimerDomain

public struct TimerRowActionVisibility: Equatable, Sendable { public let isHovered: Bool; public let isFocused: Bool; public var showsActions: Bool { isHovered || isFocused } }

public struct TimerListView: View {
    @ObservedObject var state: AppState
    public init(state: AppState) { self.state = state }
    public var body: some View { ScrollView { VStack(alignment: .leading, spacing: 0) { if state.activeTimers.isEmpty { VStack(spacing: 6) { Image(systemName: "timer"); Text("No active timers"); Text("Create one above to begin.").font(.caption).foregroundStyle(.secondary) }.frame(maxWidth: .infinity).padding() } else { ForEach(state.activeTimers.prefix(100), id: \.id) { timer in TimerRow(timer: timer, state: state); Divider() } } } }.frame(width: 340, height: 260).accessibilityIdentifier("timer-list") }
}
private struct TimerRow: View { let timer: TimerItem; @ObservedObject var state: AppState; @State private var hovered = false; @FocusState private var focused: Bool
    var body: some View { HStack { VStack(alignment: .leading, spacing: 3) { Text(timer.title.isEmpty ? "Stopwatch" : timer.title); Text(summary).font(.caption2).foregroundStyle(.secondary); if !timer.tags.isEmpty { Text(timer.tags.map { "#\($0)" }.joined(separator: " ")).font(.caption2).foregroundStyle(.secondary) }; ProgressView(value: progress).tint(.accentColor) }; Spacer(); if TimerRowActionVisibility(isHovered: hovered, isFocused: focused).showsActions { actions } }.padding(8).onHover { hovered = $0 }.focusable().focused($focused) }
    private var actions: some View { HStack { Button { Task { await state.selectEditor(timer.id) } } label: { Image(systemName: "pencil") }.help("Edit").accessibilityLabel("Edit timer"); Button { Task { _ = await state.duplicate(timer.id) } } label: { Image(systemName: "plus.square.on.square") }.help("Duplicate").accessibilityLabel("Duplicate timer"); Button { Task { _ = await state.restart(timer.id) } } label: { Image(systemName: "arrow.clockwise") }.help("Restart").accessibilityLabel("Restart timer"); Button { Task { _ = timer.state == .running ? await state.pause(timer.id) : await state.resume(timer.id) } } label: { Image(systemName: timer.state == .running ? "pause.fill" : "play.fill") }.help(timer.state == .running ? "Pause" : "Resume").accessibilityLabel(timer.state == .running ? "Pause timer" : "Resume timer"); if timer.state == .completed { Button { Task { _ = await state.acknowledge(timer.id) } } label: { Image(systemName: "checkmark") }.help("Acknowledge").accessibilityLabel("Acknowledge timer") }; Button(role: .destructive) { Task { _ = await state.softDelete(timer.id) } } label: { Image(systemName: "trash") }.help("Delete").accessibilityLabel("Delete timer") } }
    private var progress: Double { guard let duration = timer.duration, let deadline = timer.deadline else { return 0 }; return min(1, max(0, 1 - deadline.timeIntervalSinceNow / duration)) }
    private var summary: String { let recurrence: String; switch timer.recurrence { case .none: recurrence = ""; case .interval: recurrence = " · Repeats"; case .daily: recurrence = " · Daily"; case .weekdays: recurrence = " · Weekdays"; case .weekly: recurrence = " · Weekly"; case .selectedWeekdays: recurrence = " · Selected days" }; if let deadline = timer.deadline { let seconds = max(0, Int(deadline.timeIntervalSinceNow)); return String(format: "%d:%02d remaining · Ends %@%@", seconds / 60, seconds % 60, deadline.formatted(date: .omitted, time: .shortened), recurrence) }; return (timer.kind == .stopwatch ? "Stopwatch" : "Paused") + recurrence }
}
