import SwiftUI
import TopTimerDomain

public enum RecurrenceEditorMode: String, CaseIterable, Sendable { case none, interval, daily, weekdays, weekly, selectedWeekdays }
public enum EditorDraftError: Error, Equatable { case invalid(String) }
public struct EditorDraft: Equatable, Sendable {
    public var kind: TimerKind = .countdown; public var title = ""; public var details = ""; public var tags: [String] = []; public var duration: TimeInterval = 300; public var recurrenceMode: RecurrenceEditorMode = .none; public var interval: TimeInterval = 300; public var hour = 9; public var minute = 0; public var weekday = 2; public var selectedWeekdays: Set<Int> = []; public var alertName: String?; public var volume = 1.0
    public init() {}
    public init(timer: TimerItem) { kind = timer.kind; title = timer.title; details = timer.details; tags = timer.tags; duration = timer.duration ?? 300; alertName = timer.alertName; volume = timer.alertVolume; switch timer.recurrence { case .none: break; case let .interval(seconds): recurrenceMode = .interval; interval = seconds; case let .daily(hour, minute): recurrenceMode = .daily; self.hour = hour; self.minute = minute; case let .weekdays(hour, minute): recurrenceMode = .weekdays; self.hour = hour; self.minute = minute; case let .weekly(weekday, hour, minute): recurrenceMode = .weekly; self.weekday = weekday; self.hour = hour; self.minute = minute; case let .selectedWeekdays(days, hour, minute): recurrenceMode = .selectedWeekdays; selectedWeekdays = days; self.hour = hour; self.minute = minute } }
    public func configuration() throws -> TimerConfiguration { guard validationError() == nil else { throw EditorDraftError.invalid(validationError()!) }; return TimerConfiguration(kind: kind, title: title, details: details, tags: tags, duration: kind == .countdown ? duration : nil, recurrence: recurrence(), alertName: alertName, alertVolume: volume) }
    public func validationError() -> String? { if title.count > TimerLimits.title { return "Title must be 80 characters or fewer." }; if details.count > TimerLimits.details { return "Details must be 500 characters or fewer." }; if tags.count > TimerLimits.tags { return "Use at most 12 tags." }; if tags.contains(where: { $0.count > TimerLimits.tag }) { return "Tags must be 32 characters or fewer." }; if kind == .countdown && (!duration.isFinite || duration < 1 || duration > TimerLimits.maximumDuration) { return "Duration must be between 1 second and 1 year." }; if !volume.isFinite || !(0...1).contains(volume) { return "Volume must be between 0 and 1." }; if recurrenceMode == .interval && (!interval.isFinite || interval < 1 || interval > TimerLimits.maximumDuration) { return "Interval must be between 1 second and 1 year." }; if recurrenceMode == .selectedWeekdays && selectedWeekdays.isEmpty { return "Choose at least one weekday." }; if kind == .stopwatch && recurrenceMode != .none { return "Stopwatches cannot recur." }; return nil }
    private func recurrence() -> RecurrenceRule { switch recurrenceMode { case .none: .none; case .interval: .interval(seconds: interval); case .daily: .daily(hour: hour, minute: minute); case .weekdays: .weekdays(hour: hour, minute: minute); case .weekly: .weekly(weekday: weekday, hour: hour, minute: minute); case .selectedWeekdays: .selectedWeekdays(weekdays: selectedWeekdays, hour: hour, minute: minute) } }
}
public struct TimerEditorView: View {
    @Binding var draft: EditorDraft; let save: (TimerConfiguration) async -> Bool; @Environment(\.dismiss) private var dismiss
    public init(draft: Binding<EditorDraft>, save: @escaping (TimerConfiguration) async -> Bool) { _draft = draft; self.save = save }
    public var body: some View { Form { Picker("Timer type", selection: $draft.kind) { Text("Countdown").tag(TimerKind.countdown); Text("Stopwatch").tag(TimerKind.stopwatch) }; TextField("Title", text: $draft.title).accessibilityIdentifier("timer-editor-title"); TextField("Details", text: $draft.details, axis: .vertical); TextField("Tags", text: Binding(get: { draft.tags.joined(separator: ", ") }, set: { draft.tags = $0.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) } })); if draft.kind == .countdown { Stepper("Duration: \(Int(draft.duration)) seconds", value: $draft.duration, in: 1...TimerLimits.maximumDuration) }; Picker("Repeat", selection: $draft.recurrenceMode) { ForEach(RecurrenceEditorMode.allCases, id: \.self) { Text($0.rawValue).tag($0) } }; if draft.recurrenceMode == .interval { Stepper("Interval: \(Int(draft.interval)) seconds", value: $draft.interval, in: 1...TimerLimits.maximumDuration) }; if [.daily, .weekdays, .weekly, .selectedWeekdays].contains(draft.recurrenceMode) { Stepper("Hour: \(draft.hour)", value: $draft.hour, in: 0...23); Stepper("Minute: \(draft.minute)", value: $draft.minute, in: 0...59) }; if draft.recurrenceMode == .weekly { Picker("Weekday", selection: $draft.weekday) { ForEach(1...7, id: \.self) { Text("Day \($0)").tag($0) } } }; if draft.recurrenceMode == .selectedWeekdays { ForEach(1...7, id: \.self) { day in Toggle("Day \(day)", isOn: Binding(get: { draft.selectedWeekdays.contains(day) }, set: { enabled in if enabled { draft.selectedWeekdays.insert(day) } else { draft.selectedWeekdays.remove(day) } })) } }; Picker("Alert sound", selection: Binding(get: { draft.alertName ?? "" }, set: { draft.alertName = $0.isEmpty ? nil : $0 })) { Text("Default").tag(""); if let name = draft.alertName { Text(name).tag(name) } }; Slider(value: $draft.volume, in: 0...1) { Text("Volume") }; if let error = draft.validationError() { Text(error).foregroundStyle(.red).accessibilityLabel(error) } }.padding().frame(width: 360).toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("Save") { Task { guard let configuration = try? draft.configuration(), await save(configuration) else { return }; dismiss() } }.disabled(draft.validationError() != nil) } } }
}
