import SwiftUI
import TopTimerDomain

public enum RecurrenceEditorMode: String, CaseIterable, Sendable { case none, interval, daily, weekdays, weekly, selectedWeekdays }
public enum EditorDraftError: Error, Equatable { case invalid(String) }
public struct SoundCatalog: Equatable, Sendable { public let names: [String]; public init(names: [String]) { self.names = Array(Set(names.filter { !$0.isEmpty })).sorted() }; public static let builtIn = SoundCatalog(names: ["Glass"]) }
public struct EditorDraft: Equatable, Sendable {
    public var kind: TimerKind = .countdown; public var title = ""; public var details = ""; public var tags: [String] = []; public var duration: TimeInterval = 300; public var recurrenceMode: RecurrenceEditorMode = .none; public var interval: TimeInterval = 300; public var hour = 9; public var minute = 0; public var weekday = 2; public var selectedWeekdays: Set<Int> = []; public var alertName: String?; public var volume = 1.0
    public init() {}
    public init(timer: TimerItem) { kind = timer.kind; title = timer.title; details = timer.details; tags = timer.tags; duration = timer.duration ?? 300; alertName = timer.alertName; volume = timer.alertVolume; switch timer.recurrence { case .none: break; case let .interval(seconds): recurrenceMode = .interval; interval = seconds; case let .daily(hour, minute): recurrenceMode = .daily; self.hour = hour; self.minute = minute; case let .weekdays(hour, minute): recurrenceMode = .weekdays; self.hour = hour; self.minute = minute; case let .weekly(weekday, hour, minute): recurrenceMode = .weekly; self.weekday = weekday; self.hour = hour; self.minute = minute; case let .selectedWeekdays(days, hour, minute): recurrenceMode = .selectedWeekdays; selectedWeekdays = days; self.hour = hour; self.minute = minute } }
    public func configuration(catalog: SoundCatalog = .builtIn) throws -> TimerConfiguration { guard validationError() == nil else { throw EditorDraftError.invalid(validationError()!) }; if let alertName, !catalog.names.contains(alertName) { throw EditorDraftError.invalid("Choose an available alert sound.") }; return TimerConfiguration(kind: kind, title: title, details: details, tags: tags, duration: kind == .countdown ? duration : nil, recurrence: recurrence(), alertName: alertName, alertVolume: volume) }
    public func validationError() -> String? { if title.count > TimerLimits.title { return "Title must be 80 characters or fewer." }; if details.count > TimerLimits.details { return "Details must be 500 characters or fewer." }; if tags.count > TimerLimits.tags { return "Use at most 12 tags." }; if tags.contains(where: { $0.count > TimerLimits.tag }) { return "Tags must be 32 characters or fewer." }; if kind == .countdown && (!duration.isFinite || duration < 1 || duration > TimerLimits.maximumDuration) { return "Duration must be between 1 second and 1 year." }; if !volume.isFinite || !(0...1).contains(volume) { return "Volume must be between 0 and 1." }; if recurrenceMode == .interval && (!interval.isFinite || interval < 1 || interval > TimerLimits.maximumDuration) { return "Interval must be between 1 second and 1 year." }; if recurrenceMode == .selectedWeekdays && selectedWeekdays.isEmpty { return "Choose at least one weekday." }; if kind == .stopwatch && recurrenceMode != .none { return "Stopwatches cannot recur." }; return nil }
    private func recurrence() -> RecurrenceRule { switch recurrenceMode { case .none: .none; case .interval: .interval(seconds: interval); case .daily: .daily(hour: hour, minute: minute); case .weekdays: .weekdays(hour: hour, minute: minute); case .weekly: .weekly(weekday: weekday, hour: hour, minute: minute); case .selectedWeekdays: .selectedWeekdays(weekdays: selectedWeekdays, hour: hour, minute: minute) } }
}
public struct TimerEditorView: View {
    @Binding var draft: EditorDraft; let save: (TimerConfiguration) async -> Bool; let catalog: SoundCatalog; @State private var error: String?; @Environment(\.dismiss) private var dismiss
    public init(draft: Binding<EditorDraft>, catalog: SoundCatalog = .builtIn, save: @escaping (TimerConfiguration) async -> Bool) { _draft = draft; self.catalog = catalog; self.save = save }
    public var body: some View { Form { Picker("Timer type", selection: $draft.kind) { Text("Countdown").tag(TimerKind.countdown); Text("Stopwatch").tag(TimerKind.stopwatch) }; TextField("Title", text: $draft.title).accessibilityIdentifier("timer-editor-title"); TextField("Details", text: $draft.details, axis: .vertical); TextField("Tags", text: Binding(get: { draft.tags.joined(separator: ", ") }, set: { draft.tags = $0.split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) } })); Picker("Alert sound", selection: Binding(get: { draft.alertName ?? "" }, set: { draft.alertName = $0.isEmpty ? nil : $0 })) { Text("Default").tag(""); ForEach(catalog.names, id: \.self) { Text($0).tag($0) } }; Slider(value: $draft.volume, in: 0...1) { Text("Volume") }; if let error = error ?? draft.validationError() { Text(error).foregroundStyle(.red).accessibilityLabel(error) } }.padding().frame(width: 360).toolbar { ToolbarItem(placement: .confirmationAction) { Button("Save") { Task { do { let configuration = try draft.configuration(catalog: catalog); guard await save(configuration) else { error = "Could not save timer."; return }; dismiss() } catch { self.error = (error as? EditorDraftError).map { if case let .invalid(message) = $0 { message } else { "Invalid timer configuration." } } ?? "Invalid timer configuration." } } } } } }
}
